"""
Question source for the automatic quiz system.

The rest of the codebase has no existing AI text-generation integration
(no chat-completion API is wired up anywhere in this project), so rather
than bolting on an untested external call that could silently fail or
hang inside a background scheduler, this ships a curated, hand-checked
question bank instead: every question here has exactly one unambiguous
correct answer, which the FINAL BEHAVIOR spec requires.

`pick_question()` is the single entry point the quiz plugin calls. If you
later want to swap in a real AI text-generation API, that's the one
function to change — everything else (dedup, category rotation, DB
storage) stays the same.
"""

import random

# Each question: {"q": str, "options": [4 strings], "correct": index 0-3}
QUESTION_BANK = {
    "General Knowledge": [
        {"q": "दुनिया का सबसे बड़ा महासागर कौन सा है?",
         "options": ["अटलांटिक महासागर", "प्रशांत महासागर", "हिंद महासागर", "आर्कटिक महासागर"], "correct": 1},
        {"q": "साल में कितने महीने होते हैं?",
         "options": ["10", "11", "12", "13"], "correct": 2},
        {"q": "इंसान के शरीर में सबसे बड़ा अंग कौन सा है?",
         "options": ["दिल", "त्वचा (Skin)", "लीवर", "दिमाग"], "correct": 1},
        {"q": "एक हफ्ते में कितने दिन होते हैं?",
         "options": ["5", "6", "7", "8"], "correct": 2},
        {"q": "सबसे तेज़ ग्रह कौन सा है (सूरज का सबसे नज़दीकी)?",
         "options": ["बुध (Mercury)", "शुक्र (Venus)", "मंगल (Mars)", "पृथ्वी"], "correct": 0},
        {"q": "Ek din mein kitne hours hote hain?",
         "options": ["12", "20", "24", "30"], "correct": 2},
        {"q": "Human body ka normal temperature kitna hota hai (Fahrenheit mein)?",
         "options": ["86°F", "98.6°F", "110°F", "120°F"], "correct": 1},
        {"q": "Duniya ka sabse bada continent kaunsa hai?",
         "options": ["Africa", "Asia", "Europe", "North America"], "correct": 1},
        {"q": "Duniya ka sabse chhota desh kaunsa hai (area ke hisaab se)?",
         "options": ["Monaco", "Vatican City", "Malta", "San Marino"], "correct": 1},
        {"q": "Insaan ke dil mein kitne chambers hote hain?",
         "options": ["2", "3", "4", "5"], "correct": 2},
        {"q": "Sabse bada organ jo humein bahar se dikhta hai kaunsa hai?",
         "options": ["Liver", "Skin", "Heart", "Lungs"], "correct": 1},
        {"q": "Ek normal adult insaan ke kitne teeth (permanent) hote hain?",
         "options": ["28", "30", "32", "34"], "correct": 2},
        {"q": "Duniya ki sabse oonchi (tallest) building kaunsi hai?",
         "options": ["Burj Khalifa", "Shanghai Tower", "Eiffel Tower", "Taipei 101"], "correct": 0},
        {"q": "Photosynthesis ka main output gas kaunsa hai?",
         "options": ["Carbon Dioxide", "Nitrogen", "Oxygen", "Hydrogen"], "correct": 2},
        {"q": "Duniya ki sabse choti gaay... nahi, sabse tez zameeni jaanwar kaunsa hai?",
         "options": ["Cheetah", "Lion", "Horse", "Tiger"], "correct": 0},
        {"q": "Duniya mein kitne mahadesh (continents) hote hain?",
         "options": ["5", "6", "7", "8"], "correct": 2},
        {"q": "Sabse chhota planet (grah) hamare solar system mein kaunsa hai?",
         "options": ["Mars", "Mercury", "Venus", "Pluto"], "correct": 1},
        {"q": "Duniya ka sabse lamba jaanwar (gala/height ke hisaab se) kaunsa hai?",
         "options": ["Elephant", "Giraffe", "Camel", "Horse"], "correct": 1},
        {"q": "Human blood ka rang laal kis element ki wajah se hota hai?",
         "options": ["Calcium", "Iron", "Sodium", "Zinc"], "correct": 1},
        {"q": "Duniya mein sabse zyada bola jaane wala language kaunsa hai (native speakers)?",
         "options": ["English", "Spanish", "Mandarin Chinese", "Hindi"], "correct": 2},
        {"q": "1 kilometer mein kitne meter hote hain?",
         "options": ["100", "1000", "10000", "10"], "correct": 1},
        {"q": "1 meter mein kitne centimeter hote hain?",
         "options": ["10", "100", "1000", "50"], "correct": 1},
        {"q": "1 kilogram mein kitne gram hote hain?",
         "options": ["100", "500", "1000", "10000"], "correct": 2},
        {"q": "1 ghanta mein kitne minute hote hain?",
         "options": ["30", "45", "60", "90"], "correct": 2},
        {"q": "1 minute mein kitne second hote hain?",
         "options": ["30", "60", "100", "120"], "correct": 1},
        {"q": "1 saal mein kitne din hote hain (normal saal)?",
         "options": ["360", "364", "365", "366"], "correct": 2},
        {"q": "Leap year mein February mein kitne din hote hain?",
         "options": ["27", "28", "29", "30"], "correct": 2},
        {"q": "1 dozen mein kitni cheezein hoti hain?",
         "options": ["10", "12", "14", "16"], "correct": 1},
        {"q": "1 litre mein kitne millilitre hote hain?",
         "options": ["100", "500", "1000", "10000"], "correct": 2},
        {"q": "1 saal mein kitne hafte (weeks) hote hain (approx)?",
         "options": ["42", "48", "52", "58"], "correct": 2},
        {"q": "1 din mein kitne minute hote hain?",
         "options": ["1000", "1220", "1440", "1600"], "correct": 2},
        {"q": "1 GB mein kitne MB hote hain (approx)?",
         "options": ["100", "512", "1000", "1024"], "correct": 3},
        {"q": "1 MB mein kitne KB hote hain (approx)?",
         "options": ["100", "512", "1000", "1024"], "correct": 3},
        {"q": "Ek decade mein kitne saal hote hain?",
         "options": ["5", "10", "50", "100"], "correct": 1},
        {"q": "Ek century mein kitne saal hote hain?",
         "options": ["10", "50", "100", "1000"], "correct": 2},
        {"q": "1 rupee mein kitne paise hote hain?",
         "options": ["10", "50", "100", "1000"], "correct": 2},
        {"q": "Ek hafte (week) mein kitne din hote hain?",
         "options": ["5", "6", "7", "8"], "correct": 2},
        {"q": "Saal ka pehla mahina kaunsa hota hai?",
         "options": ["December", "January", "March", "April"], "correct": 1},
        {"q": "Saal ka aakhri (last) mahina kaunsa hota hai?",
         "options": ["November", "December", "October", "January"], "correct": 1},
        {"q": "Ek din mein kitne ghante hote hain?",
         "options": ["12", "20", "24", "26"], "correct": 2},
        {"q": "1 ton mein kitne kilogram hote hain?",
         "options": ["100", "500", "1000", "10000"], "correct": 2},
        {"q": "Human body mein kitne senses (indriyan) hoti hain (traditionally)?",
         "options": ["3", "4", "5", "6"], "correct": 2},
        {"q": "Rainbow (dhanush) mein kitne colours hote hain?",
         "options": ["5", "6", "7", "8"], "correct": 2},
        {"q": "Ek triangle mein kitne sides hoti hain?",
         "options": ["2", "3", "4", "5"], "correct": 1},
        {"q": "Ek square mein kitne sides hoti hain?",
         "options": ["3", "4", "5", "6"], "correct": 1},
        {"q": "Ek hexagon mein kitni sides hoti hain?",
         "options": ["5", "6", "7", "8"], "correct": 1},
        {"q": "Straight line ka angle kitne degree ka hota hai?",
         "options": ["90", "120", "180", "360"], "correct": 2},
        {"q": "Ek right angle kitne degree ka hota hai?",
         "options": ["45", "60", "90", "120"], "correct": 2},
        {"q": "Full circle kitne degree ka hota hai?",
         "options": ["90", "180", "270", "360"], "correct": 3},
        {"q": "1 inch mein approx kitne centimeter hote hain?",
         "options": ["1.5", "2.5", "3.5", "5"], "correct": 1},
    ],
    "Indian GK": [
        {"q": "भारत का राष्ट्रीय पशु कौन सा है?",
         "options": ["शेर", "बाघ", "हाथी", "हिरण"], "correct": 1},
        {"q": "भारत की राजधानी कौन सी है?",
         "options": ["मुंबई", "कोलकाता", "नई दिल्ली", "चेन्नई"], "correct": 2},
        {"q": "भारत का राष्ट्रीय पक्षी कौन सा है?",
         "options": ["मोर", "कबूतर", "तोता", "बुलबुल"], "correct": 0},
        {"q": "भारत की सबसे लंबी नदी कौन सी है?",
         "options": ["यमुना", "गंगा", "ब्रह्मपुत्र", "गोदावरी"], "correct": 1},
        {"q": "भारत को आज़ादी किस साल मिली?",
         "options": ["1942", "1945", "1947", "1950"], "correct": 2},
        {"q": "India ka national game officially kya hai?",
         "options": ["Cricket", "Hockey", "Kabaddi", "Football"], "correct": 1},
        {"q": "Bharat ke kitne states hain (as of ab)?",
         "options": ["26", "28", "29", "31"], "correct": 1},
        {"q": "Bharat ka sabse bada state (area ke hisaab se) kaunsa hai?",
         "options": ["Madhya Pradesh", "Rajasthan", "Maharashtra", "Uttar Pradesh"], "correct": 1},
        {"q": "Bharat ki sabse zyada population wali city kaunsi hai?",
         "options": ["Delhi", "Mumbai", "Bangalore", "Kolkata"], "correct": 1},
        {"q": "Bharat ka national flower kaunsa hai?",
         "options": ["Rose", "Lotus", "Sunflower", "Marigold"], "correct": 1},
        {"q": "Bharat ka pehla Prime Minister kaun tha?",
         "options": ["Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Patel", "Dr. Rajendra Prasad"], "correct": 1},
        {"q": "Bharat ka Rashtriya Chinh (National Emblem) kahan se liya gaya hai?",
         "options": ["Ashoka Stambh (Sarnath)", "Qutub Minar", "Lal Kila", "Konark Temple"], "correct": 0},
        {"q": "Bharat mein currency ka naam kya hai?",
         "options": ["Dinar", "Rupee", "Dollar", "Taka"], "correct": 1},
        {"q": "Bharat ki national currency symbol (₹) kis saal official hua tha?",
         "options": ["2005", "2010", "2015", "2020"], "correct": 1},
        {"q": "\"Jana Gana Mana\" kis bhasha mein likha gaya hai?",
         "options": ["Hindi", "Bengali", "Sanskrit", "Tamil"], "correct": 1},
        {"q": "Bharat ka sabse ooncha pahad (peak) kaunsa hai?",
         "options": ["Nanda Devi", "Kanchenjunga", "K2", "Everest"], "correct": 1},
        {"q": "Bharat mein Lok Sabha ke total kitne seats hain?",
         "options": ["525", "543", "552", "560"], "correct": 1},
        {"q": "Bharat ka sabse bada registered religion (population ke hisaab se) kaunsa hai?",
         "options": ["Islam", "Christianity", "Hinduism", "Sikhism"], "correct": 2},
        {"q": "Bharat ka Rashtrapati Bhawan kis city mein hai?",
         "options": ["Mumbai", "New Delhi", "Kolkata", "Chennai"], "correct": 1},
        {"q": "India Gate kis city mein hai?",
         "options": ["Mumbai", "New Delhi", "Agra", "Jaipur"], "correct": 1},
    ],
    "Movies": [
        {"q": "बॉलीवुड की सबसे पुरानी फिल्म इंडस्ट्री किस शहर में है?",
         "options": ["दिल्ली", "मुंबई", "चेन्नई", "कोलकाता"], "correct": 1},
        {"q": "\"3 Idiots\" फिल्म किस उपन्यास पर आधारित है?",
         "options": ["Five Point Someone", "The White Tiger", "Chetan's Diary", "Half Girlfriend"], "correct": 0},
        {"q": "भारत में सबसे बड़ा फिल्म अवॉर्ड कौन सा माना जाता है?",
         "options": ["फिल्मफेयर अवॉर्ड", "दादासाहेब फाल्के अवॉर्ड", "स्टार स्क्रीन अवॉर्ड", "IIFA अवॉर्ड"], "correct": 1},
        {"q": "\"Sholay\" movie mein Gabbar Singh ka role kisne play kiya tha?",
         "options": ["Amjad Khan", "Amitabh Bachchan", "Dharmendra", "Sanjeev Kumar"], "correct": 0},
        {"q": "\"Dangal\" movie kis sport par based hai?",
         "options": ["Boxing", "Wrestling", "Athletics", "Badminton"], "correct": 1},
        {"q": "\"Baahubali\" movie kis language mein originally banayi gayi thi?",
         "options": ["Hindi", "Tamil", "Telugu", "Kannada"], "correct": 2},
        {"q": "Shah Rukh Khan ko Bollywood mein kis naam se jaana jaata hai?",
         "options": ["King Khan", "Bollywood Star", "Superstar", "Mega Star"], "correct": 0},
        {"q": "\"Lagaan\" movie kis khel (sport) par based hai?",
         "options": ["Hockey", "Cricket", "Football", "Kabaddi"], "correct": 1},
        {"q": "Oscar Awards har saal kis country mein diye jaate hain?",
         "options": ["UK", "France", "USA", "Canada"], "correct": 2},
        {"q": "\"RRR\" movie ka Oscar-winning song kaunsa tha?",
         "options": ["Naatu Naatu", "Jai Ho", "Kar Har Maidaan Fateh", "Malhari"], "correct": 0},
        {"q": "Amitabh Bachchan ko kis naam se bhi jaana jaata hai?",
         "options": ["Big B", "King Khan", "Chota Don", "Mega Star"], "correct": 0},
        {"q": "Marvel ke superheroes ki movies kis banner ke naam se aati hain?",
         "options": ["DC Studios", "Marvel Studios", "Pixar", "Warner Bros"], "correct": 1},
        {"q": "\"Sholay\" movie kis saal release hui thi?",
         "options": ["1970", "1975", "1980", "1985"], "correct": 1},
    ],
    "Music": [
        {"q": "भारत का राष्ट्रगान किसने लिखा था?",
         "options": ["रवींद्रनाथ टैगोर", "बंकिम चंद्र चट्टोपाध्याय", "सुभाष चंद्र बोस", "महात्मा गांधी"], "correct": 0},
        {"q": "एक सामान्य पियानो में कितनी keys होती हैं?",
         "options": ["76", "88", "96", "108"], "correct": 1},
        {"q": "भारत के सबसे मशहूर शास्त्रीय गायकों में किसे \"सुर सम्राज्ञी\" कहा जाता है?",
         "options": ["आशा भोसले", "लता मंगेशकर", "कविता कृष्णमूर्ति", "श्रेया घोषाल"], "correct": 1},
        {"q": "Guitar mein normally kitne strings hote hain?",
         "options": ["4", "5", "6", "7"], "correct": 2},
        {"q": "A.R. Rahman ne kis Bollywood movie ke liye Oscar jeeta tha?",
         "options": ["Lagaan", "Slumdog Millionaire", "3 Idiots", "Rockstar"], "correct": 1},
        {"q": "Violin ko baja ne ke liye kis chiz ka use hota hai?",
         "options": ["Stick", "Bow", "Pick", "Hammer"], "correct": 1},
        {"q": "Tabla kis type ka instrument hai?",
         "options": ["String", "Wind", "Percussion", "Brass"], "correct": 2},
        {"q": "\"Lata Mangeshkar\" ko kis field mein legend mana jaata hai?",
         "options": ["Acting", "Playback Singing", "Dance", "Direction"], "correct": 1},
        {"q": "Flute (bansuri) kis type ka instrument hai?",
         "options": ["String", "Wind", "Percussion", "Electronic"], "correct": 1},
        {"q": "Sitar bajane wale sabse famous musician kaun the?",
         "options": ["Zakir Hussain", "Ravi Shankar", "A.R. Rahman", "Ustad Bismillah Khan"], "correct": 1},
    ],
    "Cricket": [
        {"q": "क्रिकेट में एक ओवर में कितनी गेंदें होती हैं?",
         "options": ["4", "5", "6", "8"], "correct": 2},
        {"q": "भारत ने पहला क्रिकेट वर्ल्ड कप किस साल जीता था?",
         "options": ["1975", "1983", "1996", "2007"], "correct": 1},
        {"q": "क्रिकेट में \"LBW\" का मतलब क्या होता है?",
         "options": ["Leg Before Wicket", "Long Ball Wide", "Last Ball Win", "Late Batting Warning"], "correct": 0},
        {"q": "India ne T20 World Cup 2024 mein final kis team ko haraya tha?",
         "options": ["Australia", "Pakistan", "South Africa", "England"], "correct": 2},
        {"q": "Cricket mein ek innings mein maximum kitne wickets fall ho sakte hain (ek team ki)?",
         "options": ["9", "10", "11", "12"], "correct": 1},
        {"q": "Cricket mein 'Century' ka matlab kya hota hai?",
         "options": ["10 runs", "50 runs", "100 runs", "6 wickets"], "correct": 2},
        {"q": "Sachin Tendulkar ko kis naam se jaana jaata hai?",
         "options": ["God of Cricket", "King of Cricket", "Master Blaster", "Cricket Emperor"], "correct": 2},
        {"q": "ODI cricket match mein har team ke kitne overs hote hain?",
         "options": ["20", "40", "50", "60"], "correct": 2},
        {"q": "T20 cricket match mein har team ke kitne overs hote hain?",
         "options": ["10", "15", "20", "25"], "correct": 2},
        {"q": "India ne cricket World Cup 2011 kis country mein jeeta tha (host)?",
         "options": ["Australia", "England", "India", "South Africa"], "correct": 2},
        {"q": "Cricket mein ek team mein kitne players hote hain (playing XI)?",
         "options": ["9", "10", "11", "12"], "correct": 2},
        {"q": "IPL ka full form kya hai?",
         "options": ["Indian Premier League", "International Players League", "Indian Players League", "Inter Premier League"], "correct": 0},
        {"q": "Virat Kohli kis IPL team ke saath sabse zyada jude rahe hain?",
         "options": ["Mumbai Indians", "Chennai Super Kings", "Royal Challengers Bangalore", "Kolkata Knight Riders"], "correct": 2},
    ],
    "Sports": [
        {"q": "फुटबॉल के एक मैच में हर टीम के कितने खिलाड़ी मैदान पर होते हैं?",
         "options": ["9", "10", "11", "12"], "correct": 2},
        {"q": "ओलंपिक खेल कितने सालों में एक बार होते हैं?",
         "options": ["2", "3", "4", "5"], "correct": 2},
        {"q": "बैडमिंटन में शटलकॉक को मारने के लिए किसका इस्तेमाल होता है?",
         "options": ["बैट", "रैकेट", "स्टिक", "पैडल"], "correct": 1},
        {"q": "Chess board mein total kitne squares hote hain?",
         "options": ["32", "48", "64", "100"], "correct": 2},
        {"q": "FIFA World Cup kis khel se related hai?",
         "options": ["Cricket", "Football", "Hockey", "Basketball"], "correct": 1},
        {"q": "Basketball match mein ek team mein kitne players court par hote hain?",
         "options": ["4", "5", "6", "7"], "correct": 1},
        {"q": "Olympics ke logo mein kitne rings hote hain?",
         "options": ["3", "4", "5", "6"], "correct": 2},
        {"q": "Tennis mein ek match jeetne ke liye kitne sets jeetne padte hain (best of 3 mein)?",
         "options": ["1", "2", "3", "4"], "correct": 1},
        {"q": "Hockey Bharat ka purana national game officially maana jaata tha, uska origin desh kaunsa hai?",
         "options": ["India", "England", "Australia", "Pakistan"], "correct": 1},
        {"q": "Wimbledon kis sport se related tournament hai?",
         "options": ["Cricket", "Tennis", "Football", "Golf"], "correct": 1},
    ],
    "Technology": [
        {"q": "\"WWW\" का पूरा नाम क्या है?",
         "options": ["World Wide Web", "World Web Wide", "Wide World Web", "Web World Wide"], "correct": 0},
        {"q": "स्मार्टफोन में \"RAM\" किसके लिए इस्तेमाल होती है?",
         "options": ["Storage बढ़ाने के लिए", "Battery बचाने के लिए", "ऐप्स को तेज़ी से चलाने के लिए (temporary memory)", "Screen brightness बढ़ाने के लिए"], "correct": 2},
        {"q": "ChatGPT जैसे AI मॉडल्स को क्या कहा जाता है?",
         "options": ["Operating System", "Large Language Model", "Antivirus", "Firewall"], "correct": 1},
        {"q": "Android phone banane wali company kaun hai?",
         "options": ["Apple", "Google", "Microsoft", "Samsung"], "correct": 1},
        {"q": "\"HTTP\" mein \"S\" (HTTPS) kis chiz ke liye add hota hai?",
         "options": ["Speed", "Security", "Storage", "Server"], "correct": 1},
        {"q": "\"CPU\" ka full form kya hai?",
         "options": ["Central Processing Unit", "Computer Processing Unit", "Central Program Unit", "Core Processing Unit"], "correct": 0},
        {"q": "World Wide Web ko kisne invent kiya tha?",
         "options": ["Bill Gates", "Steve Jobs", "Tim Berners-Lee", "Mark Zuckerberg"], "correct": 2},
        {"q": "Facebook ke founder kaun hain?",
         "options": ["Elon Musk", "Mark Zuckerberg", "Jack Dorsey", "Bill Gates"], "correct": 1},
        {"q": "\"USB\" ka full form kya hai?",
         "options": ["Universal Serial Bus", "Unified System Bus", "Universal System Board", "United Serial Board"], "correct": 0},
        {"q": "Microsoft ke founder kaun hain?",
         "options": ["Steve Jobs", "Bill Gates", "Larry Page", "Jeff Bezos"], "correct": 1},
        {"q": "iPhone banane wali company kaunsi hai?",
         "options": ["Samsung", "Google", "Apple", "Sony"], "correct": 2},
        {"q": "\"AI\" ke context mein \"ML\" ka full form kya hai?",
         "options": ["Multiple Learning", "Machine Learning", "Meta Language", "Mobile Learning"], "correct": 1},
    ],
    "Science": [
        {"q": "पानी का रासायनिक फॉर्मूला क्या है?",
         "options": ["CO2", "H2O", "O2", "NaCl"], "correct": 1},
        {"q": "इंसान के शरीर में हड्डियों की कुल संख्या कितनी होती है (adult)?",
         "options": ["186", "206", "226", "246"], "correct": 1},
        {"q": "पृथ्वी सूरज का एक चक्कर पूरा करने में कितना समय लेती है?",
         "options": ["24 घंटे", "1 महीना", "1 साल", "10 साल"], "correct": 2},
        {"q": "Humare body mein sabse chhota bone kahan hota hai?",
         "options": ["Kaan (ear) mein", "Naak (nose) mein", "Haath (hand) mein", "Paav (foot) mein"], "correct": 0},
        {"q": "Photosynthesis process plants mein kis chiz ki help se hoti hai?",
         "options": ["Sunlight", "Moonlight", "Wind", "Sound"], "correct": 0},
        {"q": "Sabse light gas kaunsi hai?",
         "options": ["Oxygen", "Nitrogen", "Hydrogen", "Helium"], "correct": 2},
        {"q": "Sound sabse tez kis medium mein travel karti hai?",
         "options": ["Air", "Water", "Solid (jaise steel)", "Vacuum"], "correct": 2},
        {"q": "Insaan ka DNA structure kis shape ka hota hai?",
         "options": ["Circle", "Double Helix", "Triangle", "Square"], "correct": 1},
        {"q": "Gravity (gurutvakarshan) ka concept kisne diya tha?",
         "options": ["Einstein", "Newton", "Galileo", "Darwin"], "correct": 1},
        {"q": "Plants apna food kis process se banate hain?",
         "options": ["Respiration", "Photosynthesis", "Digestion", "Fermentation"], "correct": 1},
        {"q": "Insaan ke body mein blood banane ka kaam kaunsa organ karta hai?",
         "options": ["Liver", "Bone Marrow", "Kidney", "Heart"], "correct": 1},
        {"q": "Periodic table mein sabse pehla element kaunsa hai?",
         "options": ["Helium", "Oxygen", "Hydrogen", "Carbon"], "correct": 2},
    ],
    "History": [
        {"q": "ताजमहल किसने बनवाया था?",
         "options": ["अकबर", "शाहजहाँ", "औरंगज़ेब", "हुमायूं"], "correct": 1},
        {"q": "दूसरा विश्व युद्ध किस साल खत्म हुआ था?",
         "options": ["1943", "1945", "1947", "1950"], "correct": 1},
        {"q": "Mahatma Gandhi ko \"Father of the Nation\" kis desh mein kaha jaata hai?",
         "options": ["Pakistan", "India", "Bangladesh", "Nepal"], "correct": 1},
        {"q": "Bharat par British Raj kitne saalo tak raha (approx)?",
         "options": ["100 saal", "150 saal", "200 saal", "250 saal"], "correct": 2},
        {"q": "Mughal Empire ki sthapna kisne ki thi?",
         "options": ["Akbar", "Babur", "Humayun", "Shah Jahan"], "correct": 1},
        {"q": "Quit India Movement kis saal shuru hua tha?",
         "options": ["1930", "1935", "1942", "1947"], "correct": 2},
        {"q": "Dandi March (Salt March) kisne lead kiya tha?",
         "options": ["Jawaharlal Nehru", "Mahatma Gandhi", "Sardar Patel", "Subhash Chandra Bose"], "correct": 1},
        {"q": "First World War kis saal shuru hui thi?",
         "options": ["1910", "1914", "1918", "1920"], "correct": 1},
    ],
    "Geography": [
        {"q": "दुनिया का सबसे बड़ा रेगिस्तान (ठंडा रेगिस्तान छोड़कर) कौन सा है?",
         "options": ["गोबी", "थार", "सहारा", "कालाहारी"], "correct": 2},
        {"q": "माउंट एवरेस्ट किस देश में है?",
         "options": ["भारत", "नेपाल", "चीन", "भूटान"], "correct": 1},
        {"q": "Duniya ka sabse chhota continent kaun sa hai?",
         "options": ["Europe", "Antarctica", "Australia", "South America"], "correct": 2},
        {"q": "Duniya ki sabse lambi nadi kaunsi hai?",
         "options": ["Ganga", "Amazon", "Nile", "Yangtze"], "correct": 2},
        {"q": "Sahara Desert kis continent mein hai?",
         "options": ["Asia", "Africa", "Australia", "South America"], "correct": 1},
        {"q": "Duniya ka sabse bada desh (area ke hisaab se) kaunsa hai?",
         "options": ["China", "USA", "Russia", "Canada"], "correct": 2},
        {"q": "Duniya mein sabse zyada population wala desh kaunsa hai?",
         "options": ["China", "India", "USA", "Indonesia"], "correct": 1},
        {"q": "Great Wall kis desh mein hai?",
         "options": ["Japan", "China", "Korea", "Mongolia"], "correct": 1},
    ],
    "Fun Questions": [
        {"q": "अगर आप एक superpower चुन सकें, तो सबसे ज़्यादा लोग क्या चुनते हैं सर्वे में?",
         "options": ["उड़ना (Flying)", "समय रोकना", "अदृश्य होना", "दिमाग पढ़ना"], "correct": 0},
        {"q": "इमोजी 😂 का सही मतलब क्या है?",
         "options": ["रोना", "हंसते हुए रोना (हंसी के आंसू)", "गुस्सा", "हैरानी"], "correct": 1},
        {"q": "Agar aapko ek din ke liye invisible hone ki power milti, sabse zyada log kya karte (common answer surveys mein)?",
         "options": ["Dosto ko darana", "Free mein ghumna", "Kisi ki jasoosi karna", "Sona"], "correct": 1},
        {"q": "Sabse zyada log kis din ko \"weekend ka best din\" mante hain (common opinion)?",
         "options": ["Friday", "Saturday", "Sunday", "Monday"], "correct": 1},
        {"q": "Emoji 🔥 ka common use kis matlab ke liye hota hai?",
         "options": ["Garmi (hot weather)", "Kuch bahut cool/awesome hai", "Khana pak raha hai", "Danger warning"], "correct": 1},
        {"q": "\"LOL\" ka full form kya hota hai?",
         "options": ["Lots Of Love", "Laugh Out Loud", "Life Of Luxury", "Lot Of Likes"], "correct": 1},
    ],
    "Brain Teasers": [
        {"q": "अगर 2 घंटे पहले 3 बजे थे, तो अभी कितने बजे हैं?",
         "options": ["4 बजे", "5 बजे", "6 बजे", "इनमें से कोई नहीं"], "correct": 1},
        {"q": "किसी संख्या को 0 से भाग देने पर क्या होता है?",
         "options": ["वो संख्या 0 हो जाती है", "वो संख्या 1 हो जाती है", "यह गणितीय रूप से undefined है", "वो संख्या -1 हो जाती है"], "correct": 2},
        {"q": "Agar aaj Monday hai, to 100 din baad kaunsa din hoga?",
         "options": ["Monday", "Tuesday", "Wednesday", "Thursday"], "correct": 2},
        {"q": "6 x 3 kitna hota hai?",
         "options": ["15", "30", "18", "16"], "correct": 2},
        {"q": "20 x 5 kitna hota hai?",
         "options": ["88", "105", "101", "100"], "correct": 3},
        {"q": "75 + 88 kitna hota hai?",
         "options": ["166", "160", "163", "151"], "correct": 2},
        {"q": "11 x 3 kitna hota hai?",
         "options": ["45", "33", "34", "28"], "correct": 1},
        {"q": "54 + 24 kitna hota hai?",
         "options": ["78", "77", "79", "70"], "correct": 0},
        {"q": "69 + 79 kitna hota hai?",
         "options": ["148", "140", "151", "149"], "correct": 0},
        {"q": "9 x 5 kitna hota hai?",
         "options": ["33", "53", "45", "42"], "correct": 2},
        {"q": "59 + 46 kitna hota hai?",
         "options": ["105", "113", "107", "104"], "correct": 0},
        {"q": "96 + 45 kitna hota hai?",
         "options": ["133", "141", "149", "153"], "correct": 1},
        {"q": "70 + 59 kitna hota hai?",
         "options": ["129", "127", "141", "137"], "correct": 0},
        {"q": "40 + 15 kitna hota hai?",
         "options": ["53", "56", "54", "55"], "correct": 3},
        {"q": "94 + 74 kitna hota hai?",
         "options": ["169", "168", "170", "176"], "correct": 1},
        {"q": "82 + 79 kitna hota hai?",
         "options": ["161", "173", "166", "159"], "correct": 0},
        {"q": "49 - 9 kitna hota hai?",
         "options": ["32", "42", "43", "40"], "correct": 3},
        {"q": "8 x 16 kitna hota hai?",
         "options": ["128", "120", "129", "133"], "correct": 0},
        {"q": "11 x 20 kitna hota hai?",
         "options": ["228", "208", "232", "220"], "correct": 3},
        {"q": "13 x 6 kitna hota hai?",
         "options": ["76", "73", "78", "79"], "correct": 2},
        {"q": "8 x 19 kitna hota hai?",
         "options": ["150", "160", "152", "144"], "correct": 2},
        {"q": "80 + 78 kitna hota hai?",
         "options": ["146", "163", "158", "157"], "correct": 2},
        {"q": "60 - 16 kitna hota hai?",
         "options": ["41", "32", "49", "44"], "correct": 3},
        {"q": "79 + 27 kitna hota hai?",
         "options": ["106", "108", "101", "114"], "correct": 0},
        {"q": "80 + 36 kitna hota hai?",
         "options": ["116", "117", "128", "114"], "correct": 0},
        {"q": "42 + 39 kitna hota hai?",
         "options": ["69", "81", "73", "80"], "correct": 1},
        {"q": "20 + 91 kitna hota hai?",
         "options": ["108", "103", "99", "111"], "correct": 3},
        {"q": "10 x 11 kitna hota hai?",
         "options": ["110", "118", "107", "112"], "correct": 0},
        {"q": "71 + 63 kitna hota hai?",
         "options": ["134", "131", "142", "126"], "correct": 0},
        {"q": "80 - 7 kitna hota hai?",
         "options": ["73", "65", "81", "61"], "correct": 0},
        {"q": "42 + 35 kitna hota hai?",
         "options": ["74", "77", "79", "80"], "correct": 1},
        {"q": "80 - 32 kitna hota hai?",
         "options": ["40", "50", "51", "48"], "correct": 3},
        {"q": "41 + 32 kitna hota hai?",
         "options": ["74", "75", "73", "70"], "correct": 2},
        {"q": "21 - 13 kitna hota hai?",
         "options": ["9", "10", "8", "6"], "correct": 2},
        {"q": "48 - 4 kitna hota hai?",
         "options": ["47", "56", "49", "44"], "correct": 3},
        {"q": "17 + 85 kitna hota hai?",
         "options": ["104", "97", "105", "102"], "correct": 3},
        {"q": "19 + 87 kitna hota hai?",
         "options": ["98", "114", "106", "103"], "correct": 2},
        {"q": "4 x 5 kitna hota hai?",
         "options": ["21", "20", "25", "28"], "correct": 1},
        {"q": "13 x 10 kitna hota hai?",
         "options": ["130", "125", "128", "131"], "correct": 0},
        {"q": "12 + 69 kitna hota hai?",
         "options": ["81", "86", "84", "73"], "correct": 0},
        {"q": "55 + 19 kitna hota hai?",
         "options": ["74", "73", "71", "72"], "correct": 0},
        {"q": "19 x 3 kitna hota hai?",
         "options": ["60", "65", "55", "57"], "correct": 3},
        {"q": "24 + 81 kitna hota hai?",
         "options": ["105", "103", "110", "100"], "correct": 0},
        {"q": "98 + 92 kitna hota hai?",
         "options": ["192", "188", "190", "193"], "correct": 2},
        {"q": "16 x 11 kitna hota hai?",
         "options": ["175", "171", "176", "164"], "correct": 2},
        {"q": "16 x 20 kitna hota hai?",
         "options": ["332", "320", "308", "312"], "correct": 1},
        {"q": "95 - 71 kitna hota hai?",
         "options": ["12", "24", "25", "19"], "correct": 1},
        {"q": "47 - 44 kitna hota hai?",
         "options": ["0", "3", "2", "11"], "correct": 1},
        {"q": "31 + 33 kitna hota hai?",
         "options": ["52", "64", "65", "59"], "correct": 1},
        {"q": "41 - 7 kitna hota hai?",
         "options": ["36", "22", "34", "35"], "correct": 2},
        {"q": "60 - 53 kitna hota hai?",
         "options": ["15", "7", "8", "4"], "correct": 1},
        {"q": "65 - 52 kitna hota hai?",
         "options": ["12", "16", "21", "13"], "correct": 3},
        {"q": "85 + 44 kitna hota hai?",
         "options": ["129", "117", "121", "134"], "correct": 0},
        {"q": "98 - 66 kitna hota hai?",
         "options": ["33", "32", "37", "24"], "correct": 1},
        {"q": "16 x 3 kitna hota hai?",
         "options": ["48", "51", "60", "56"], "correct": 0},
        {"q": "96 + 53 kitna hota hai?",
         "options": ["157", "154", "148", "149"], "correct": 3},
        {"q": "12 x 16 kitna hota hai?",
         "options": ["193", "192", "191", "204"], "correct": 1},
        {"q": "64 + 96 kitna hota hai?",
         "options": ["160", "172", "161", "168"], "correct": 0},
        {"q": "91 - 1 kitna hota hai?",
         "options": ["90", "87", "88", "91"], "correct": 0},
        {"q": "48 - 33 kitna hota hai?",
         "options": ["27", "10", "17", "15"], "correct": 3},
        {"q": "41 + 97 kitna hota hai?",
         "options": ["136", "133", "135", "138"], "correct": 3},
        {"q": "99 - 10 kitna hota hai?",
         "options": ["89", "91", "90", "97"], "correct": 0},
        {"q": "72 - 32 kitna hota hai?",
         "options": ["35", "48", "52", "40"], "correct": 3},
        {"q": "33 + 77 kitna hota hai?",
         "options": ["113", "98", "110", "112"], "correct": 2},
        {"q": "70 + 96 kitna hota hai?",
         "options": ["166", "169", "171", "165"], "correct": 0},
        {"q": "17 x 8 kitna hota hai?",
         "options": ["136", "134", "148", "138"], "correct": 0},
        {"q": "18 x 10 kitna hota hai?",
         "options": ["182", "178", "180", "172"], "correct": 2},
        {"q": "61 - 58 kitna hota hai?",
         "options": ["6", "3", "4", "0"], "correct": 1},
        {"q": "64 + 63 kitna hota hai?",
         "options": ["129", "130", "127", "126"], "correct": 2},
        {"q": "70 - 3 kitna hota hai?",
         "options": ["69", "68", "72", "67"], "correct": 3},
        {"q": "74 - 69 kitna hota hai?",
         "options": ["17", "5", "10", "8"], "correct": 1},
        {"q": "76 - 63 kitna hota hai?",
         "options": ["1", "13", "12", "14"], "correct": 1},
        {"q": "37 - 35 kitna hota hai?",
         "options": ["3", "10", "7", "2"], "correct": 3},
        {"q": "70 + 34 kitna hota hai?",
         "options": ["102", "105", "104", "92"], "correct": 2},
        {"q": "64 - 49 kitna hota hai?",
         "options": ["16", "13", "15", "7"], "correct": 2},
        {"q": "49 - 42 kitna hota hai?",
         "options": ["15", "12", "7", "4"], "correct": 2},
        {"q": "35 - 14 kitna hota hai?",
         "options": ["33", "23", "21", "19"], "correct": 2},
        {"q": "50 + 24 kitna hota hai?",
         "options": ["62", "74", "72", "79"], "correct": 1},
        {"q": "86 + 91 kitna hota hai?",
         "options": ["169", "177", "174", "189"], "correct": 1},
        {"q": "4 x 14 kitna hota hai?",
         "options": ["59", "64", "56", "57"], "correct": 2},
        {"q": "64 + 73 kitna hota hai?",
         "options": ["136", "137", "129", "138"], "correct": 1},
        {"q": "43 - 34 kitna hota hai?",
         "options": ["9", "14", "17", "7"], "correct": 0},
        {"q": "11 x 13 kitna hota hai?",
         "options": ["141", "140", "143", "135"], "correct": 2},
        {"q": "15 x 13 kitna hota hai?",
         "options": ["197", "195", "183", "194"], "correct": 1},
        {"q": "54 - 22 kitna hota hai?",
         "options": ["44", "32", "30", "37"], "correct": 1},
        {"q": "63 + 73 kitna hota hai?",
         "options": ["136", "139", "148", "133"], "correct": 0},
        {"q": "23 - 3 kitna hota hai?",
         "options": ["20", "18", "21", "17"], "correct": 0},
        {"q": "91 - 68 kitna hota hai?",
         "options": ["23", "22", "24", "35"], "correct": 0},
        {"q": "60 - 17 kitna hota hai?",
         "options": ["35", "43", "55", "40"], "correct": 1},
        {"q": "20 x 8 kitna hota hai?",
         "options": ["160", "162", "157", "172"], "correct": 0},
        {"q": "35 + 48 kitna hota hai?",
         "options": ["80", "78", "83", "82"], "correct": 2},
        {"q": "26 - 2 kitna hota hai?",
         "options": ["24", "22", "36", "27"], "correct": 0},
        {"q": "12 + 84 kitna hota hai?",
         "options": ["94", "95", "96", "98"], "correct": 2},
        {"q": "35 - 5 kitna hota hai?",
         "options": ["32", "22", "31", "30"], "correct": 3},
        {"q": "12 x 5 kitna hota hai?",
         "options": ["57", "60", "52", "63"], "correct": 1},
        {"q": "15 x 17 kitna hota hai?",
         "options": ["260", "255", "257", "253"], "correct": 1},
        {"q": "6 x 9 kitna hota hai?",
         "options": ["51", "52", "62", "54"], "correct": 3},
        {"q": "81 + 20 kitna hota hai?",
         "options": ["101", "96", "89", "102"], "correct": 0},
        {"q": "25 - 8 kitna hota hai?",
         "options": ["19", "15", "29", "17"], "correct": 3},
        {"q": "96 - 85 kitna hota hai?",
         "options": ["12", "11", "3", "8"], "correct": 1},
        {"q": "39 - 5 kitna hota hai?",
         "options": ["22", "34", "32", "29"], "correct": 1},
        {"q": "59 - 45 kitna hota hai?",
         "options": ["12", "14", "17", "15"], "correct": 1},
        {"q": "4 x 16 kitna hota hai?",
         "options": ["76", "63", "64", "69"], "correct": 2},
        {"q": "97 + 84 kitna hota hai?",
         "options": ["169", "181", "189", "186"], "correct": 1},
        {"q": "71 + 77 kitna hota hai?",
         "options": ["148", "150", "156", "146"], "correct": 0},
        {"q": "18 x 5 kitna hota hai?",
         "options": ["92", "90", "89", "91"], "correct": 1},
        {"q": "53 + 63 kitna hota hai?",
         "options": ["128", "116", "114", "118"], "correct": 1},
        {"q": "32 - 11 kitna hota hai?",
         "options": ["19", "21", "20", "13"], "correct": 1},
        {"q": "20 x 17 kitna hota hai?",
         "options": ["340", "328", "341", "337"], "correct": 0},
        {"q": "17 x 4 kitna hota hai?",
         "options": ["68", "66", "71", "65"], "correct": 0},
        {"q": "18 x 6 kitna hota hai?",
         "options": ["116", "108", "113", "96"], "correct": 1},
        {"q": "91 - 2 kitna hota hai?",
         "options": ["90", "92", "89", "81"], "correct": 2},
        {"q": "93 + 30 kitna hota hai?",
         "options": ["123", "135", "121", "125"], "correct": 0},
        {"q": "52 - 30 kitna hota hai?",
         "options": ["23", "22", "17", "25"], "correct": 1},
        {"q": "46 + 64 kitna hota hai?",
         "options": ["109", "108", "113", "110"], "correct": 3},
        {"q": "18 x 7 kitna hota hai?",
         "options": ["126", "128", "125", "129"], "correct": 0},
        {"q": "62 - 56 kitna hota hai?",
         "options": ["18", "11", "6", "3"], "correct": 2},
        {"q": "51 + 71 kitna hota hai?",
         "options": ["123", "122", "134", "130"], "correct": 1},
        {"q": "75 + 86 kitna hota hai?",
         "options": ["163", "160", "153", "161"], "correct": 3},
        {"q": "29 + 63 kitna hota hai?",
         "options": ["92", "84", "100", "87"], "correct": 0},
        {"q": "15 x 5 kitna hota hai?",
         "options": ["75", "83", "74", "78"], "correct": 0},
        {"q": "91 + 98 kitna hota hai?",
         "options": ["186", "187", "201", "189"], "correct": 3},
        {"q": "6 x 17 kitna hota hai?",
         "options": ["114", "97", "100", "102"], "correct": 3},
        {"q": "48 + 56 kitna hota hai?",
         "options": ["104", "103", "99", "105"], "correct": 0},
        {"q": "8 x 8 kitna hota hai?",
         "options": ["56", "64", "59", "69"], "correct": 1},
        {"q": "95 - 19 kitna hota hai?",
         "options": ["76", "78", "73", "84"], "correct": 0},
        {"q": "3 x 17 kitna hota hai?",
         "options": ["59", "54", "51", "49"], "correct": 2},
        {"q": "96 - 39 kitna hota hai?",
         "options": ["57", "69", "65", "58"], "correct": 0},
        {"q": "60 + 72 kitna hota hai?",
         "options": ["132", "129", "133", "124"], "correct": 0},
        {"q": "12 x 3 kitna hota hai?",
         "options": ["34", "37", "44", "36"], "correct": 3},
        {"q": "18 x 12 kitna hota hai?",
         "options": ["215", "216", "213", "221"], "correct": 1},
        {"q": "11 x 7 kitna hota hai?",
         "options": ["85", "77", "65", "69"], "correct": 1},
        {"q": "14 x 7 kitna hota hai?",
         "options": ["96", "97", "98", "90"], "correct": 2},
        {"q": "80 + 57 kitna hota hai?",
         "options": ["137", "135", "132", "140"], "correct": 0},
        {"q": "30 - 5 kitna hota hai?",
         "options": ["25", "33", "37", "22"], "correct": 0},
        {"q": "61 + 12 kitna hota hai?",
         "options": ["73", "76", "65", "71"], "correct": 0},
        {"q": "15 x 14 kitna hota hai?",
         "options": ["202", "218", "210", "207"], "correct": 2},
        {"q": "10 x 5 kitna hota hai?",
         "options": ["50", "58", "62", "52"], "correct": 0},
        {"q": "28 + 16 kitna hota hai?",
         "options": ["32", "42", "46", "44"], "correct": 3},
        {"q": "7 x 15 kitna hota hai?",
         "options": ["104", "105", "113", "107"], "correct": 1},
        {"q": "33 - 32 kitna hota hai?",
         "options": ["6", "2", "1", "13"], "correct": 2},
        {"q": "51 - 24 kitna hota hai?",
         "options": ["19", "35", "27", "26"], "correct": 2},
        {"q": "45 - 8 kitna hota hai?",
         "options": ["39", "37", "29", "45"], "correct": 1},
        {"q": "53 + 42 kitna hota hai?",
         "options": ["90", "92", "100", "95"], "correct": 3},
        {"q": "9 x 10 kitna hota hai?",
         "options": ["85", "95", "89", "90"], "correct": 3},
        {"q": "80 + 43 kitna hota hai?",
         "options": ["115", "131", "118", "123"], "correct": 3},
        {"q": "51 - 38 kitna hota hai?",
         "options": ["8", "12", "13", "1"], "correct": 2},
        {"q": "16 x 19 kitna hota hai?",
         "options": ["306", "304", "296", "316"], "correct": 1},
        {"q": "85 - 29 kitna hota hai?",
         "options": ["68", "56", "44", "61"], "correct": 1},
        {"q": "72 + 62 kitna hota hai?",
         "options": ["134", "126", "142", "135"], "correct": 0},
        {"q": "21 + 52 kitna hota hai?",
         "options": ["73", "68", "78", "65"], "correct": 0},
        {"q": "97 - 68 kitna hota hai?",
         "options": ["32", "27", "29", "31"], "correct": 2},
        {"q": "20 x 9 kitna hota hai?",
         "options": ["180", "181", "177", "182"], "correct": 0},
        {"q": "74 - 13 kitna hota hai?",
         "options": ["62", "61", "60", "69"], "correct": 1},
        {"q": "21 + 22 kitna hota hai?",
         "options": ["35", "55", "43", "44"], "correct": 2},
        {"q": "20 x 20 kitna hota hai?",
         "options": ["400", "392", "408", "399"], "correct": 0},
        {"q": "4 x 12 kitna hota hai?",
         "options": ["53", "47", "46", "48"], "correct": 3},
        {"q": "95 + 72 kitna hota hai?",
         "options": ["159", "164", "167", "166"], "correct": 2},
        {"q": "10 x 16 kitna hota hai?",
         "options": ["165", "168", "163", "160"], "correct": 3},
        {"q": "34 + 45 kitna hota hai?",
         "options": ["91", "78", "79", "77"], "correct": 2},
        {"q": "83 + 95 kitna hota hai?",
         "options": ["170", "179", "173", "178"], "correct": 3},
        {"q": "74 - 59 kitna hota hai?",
         "options": ["10", "15", "14", "13"], "correct": 1},
        {"q": "30 + 31 kitna hota hai?",
         "options": ["69", "66", "49", "61"], "correct": 3},
        {"q": "16 x 18 kitna hota hai?",
         "options": ["289", "293", "288", "290"], "correct": 2},
        {"q": "76 - 15 kitna hota hai?",
         "options": ["61", "66", "59", "69"], "correct": 0},
        {"q": "39 + 61 kitna hota hai?",
         "options": ["88", "97", "100", "105"], "correct": 2},
        {"q": "58 - 21 kitna hota hai?",
         "options": ["25", "29", "37", "39"], "correct": 2},
        {"q": "89 - 30 kitna hota hai?",
         "options": ["67", "62", "58", "59"], "correct": 3},
        {"q": "23 - 15 kitna hota hai?",
         "options": ["8", "0", "13", "7"], "correct": 0},
        {"q": "16 x 12 kitna hota hai?",
         "options": ["180", "184", "192", "193"], "correct": 2},
        {"q": "14 x 5 kitna hota hai?",
         "options": ["70", "67", "62", "71"], "correct": 0},
        {"q": "5 x 15 kitna hota hai?",
         "options": ["74", "75", "87", "73"], "correct": 1},
        {"q": "76 + 92 kitna hota hai?",
         "options": ["165", "168", "160", "171"], "correct": 1},
        {"q": "24 + 29 kitna hota hai?",
         "options": ["51", "53", "50", "48"], "correct": 1},
        {"q": "91 + 74 kitna hota hai?",
         "options": ["165", "170", "167", "173"], "correct": 0},
        {"q": "67 + 19 kitna hota hai?",
         "options": ["88", "86", "94", "84"], "correct": 1},
        {"q": "85 - 10 kitna hota hai?",
         "options": ["63", "77", "73", "75"], "correct": 3},
        {"q": "93 + 22 kitna hota hai?",
         "options": ["120", "115", "116", "118"], "correct": 1},
        {"q": "94 - 84 kitna hota hai?",
         "options": ["9", "10", "15", "7"], "correct": 1},
        {"q": "68 + 24 kitna hota hai?",
         "options": ["84", "91", "92", "104"], "correct": 2},
        {"q": "17 x 17 kitna hota hai?",
         "options": ["289", "294", "292", "284"], "correct": 0},
        {"q": "73 - 44 kitna hota hai?",
         "options": ["37", "17", "29", "34"], "correct": 2},
        {"q": "82 + 97 kitna hota hai?",
         "options": ["180", "179", "191", "177"], "correct": 1},
        {"q": "7 x 14 kitna hota hai?",
         "options": ["96", "106", "98", "110"], "correct": 2},
        {"q": "92 - 49 kitna hota hai?",
         "options": ["38", "42", "51", "43"], "correct": 3},
        {"q": "14 x 3 kitna hota hai?",
         "options": ["42", "41", "37", "40"], "correct": 0},
        {"q": "39 + 28 kitna hota hai?",
         "options": ["65", "62", "59", "67"], "correct": 3},
        {"q": "13 x 7 kitna hota hai?",
         "options": ["86", "92", "91", "96"], "correct": 2},
        {"q": "67 - 31 kitna hota hai?",
         "options": ["41", "34", "36", "38"], "correct": 2},
        {"q": "81 - 25 kitna hota hai?",
         "options": ["56", "61", "64", "55"], "correct": 0},
        {"q": "85 - 68 kitna hota hai?",
         "options": ["12", "17", "14", "18"], "correct": 1},
        {"q": "18 x 14 kitna hota hai?",
         "options": ["244", "255", "264", "252"], "correct": 3},
        {"q": "45 + 68 kitna hota hai?",
         "options": ["114", "108", "116", "113"], "correct": 3},
        {"q": "24 - 14 kitna hota hai?",
         "options": ["11", "10", "13", "9"], "correct": 1},
        {"q": "49 - 2 kitna hota hai?",
         "options": ["59", "39", "47", "46"], "correct": 2},
        {"q": "47 + 71 kitna hota hai?",
         "options": ["120", "118", "113", "130"], "correct": 1},
        {"q": "13 + 43 kitna hota hai?",
         "options": ["51", "59", "56", "53"], "correct": 2},
        {"q": "49 + 26 kitna hota hai?",
         "options": ["72", "76", "75", "63"], "correct": 2},
        {"q": "97 - 69 kitna hota hai?",
         "options": ["31", "28", "36", "16"], "correct": 1},
        {"q": "75 - 1 kitna hota hai?",
         "options": ["73", "71", "74", "79"], "correct": 2},
        {"q": "20 x 19 kitna hota hai?",
         "options": ["381", "368", "380", "383"], "correct": 2},
        {"q": "53 - 48 kitna hota hai?",
         "options": ["4", "17", "2", "5"], "correct": 3},
        {"q": "16 + 56 kitna hota hai?",
         "options": ["72", "71", "75", "80"], "correct": 0},
        {"q": "18 x 8 kitna hota hai?",
         "options": ["139", "136", "144", "156"], "correct": 2},
        {"q": "16 + 36 kitna hota hai?",
         "options": ["52", "40", "50", "51"], "correct": 0},
        {"q": "25 - 21 kitna hota hai?",
         "options": ["3", "1", "2", "4"], "correct": 3},
        {"q": "36 - 24 kitna hota hai?",
         "options": ["13", "12", "24", "14"], "correct": 1},
        {"q": "84 - 48 kitna hota hai?",
         "options": ["28", "34", "36", "39"], "correct": 2},
        {"q": "8 x 20 kitna hota hai?",
         "options": ["159", "158", "152", "160"], "correct": 3},
        {"q": "78 - 55 kitna hota hai?",
         "options": ["35", "23", "25", "18"], "correct": 1},
        {"q": "14 x 16 kitna hota hai?",
         "options": ["222", "232", "212", "224"], "correct": 3},
        {"q": "86 - 21 kitna hota hai?",
         "options": ["60", "53", "65", "70"], "correct": 2},
        {"q": "41 + 93 kitna hota hai?",
         "options": ["139", "135", "133", "134"], "correct": 3},
        {"q": "29 ka square (वर्ग) kitna hota hai?",
         "options": ["850", "843", "841", "839"], "correct": 2},
        {"q": "12 ka square (वर्ग) kitna hota hai?",
         "options": ["144", "140", "138", "153"], "correct": 0},
        {"q": "17 ka square (वर्ग) kitna hota hai?",
         "options": ["293", "289", "283", "300"], "correct": 1},
        {"q": "13 ka square (वर्ग) kitna hota hai?",
         "options": ["173", "165", "169", "180"], "correct": 2},
        {"q": "10 ka square (वर्ग) kitna hota hai?",
         "options": ["109", "98", "96", "100"], "correct": 3},
        {"q": "21 ka square (वर्ग) kitna hota hai?",
         "options": ["452", "450", "437", "441"], "correct": 3},
        {"q": "19 ka square (वर्ग) kitna hota hai?",
         "options": ["372", "361", "370", "367"], "correct": 1},
        {"q": "11 ka square (वर्ग) kitna hota hai?",
         "options": ["121", "115", "125", "117"], "correct": 0},
        {"q": "24 ka square (वर्ग) kitna hota hai?",
         "options": ["587", "572", "582", "576"], "correct": 3},
        {"q": "4 ka square (वर्ग) kitna hota hai?",
         "options": ["16", "12", "20", "18"], "correct": 0},
        {"q": "5 ka square (वर्ग) kitna hota hai?",
         "options": ["23", "27", "25", "19"], "correct": 2},
        {"q": "7 ka square (वर्ग) kitna hota hai?",
         "options": ["60", "45", "49", "43"], "correct": 2},
        {"q": "23 ka square (वर्ग) kitna hota hai?",
         "options": ["529", "523", "531", "520"], "correct": 0},
        {"q": "14 ka square (वर्ग) kitna hota hai?",
         "options": ["196", "187", "207", "205"], "correct": 0},
        {"q": "9 ka square (वर्ग) kitna hota hai?",
         "options": ["79", "81", "90", "87"], "correct": 1},
        {"q": "16 ka square (वर्ग) kitna hota hai?",
         "options": ["256", "252", "265", "247"], "correct": 0},
        {"q": "26 ka square (वर्ग) kitna hota hai?",
         "options": ["676", "680", "672", "674"], "correct": 0},
        {"q": "20 ka square (वर्ग) kitna hota hai?",
         "options": ["396", "400", "406", "404"], "correct": 1},
        {"q": "8 ka square (वर्ग) kitna hota hai?",
         "options": ["62", "68", "73", "64"], "correct": 3},
        {"q": "22 ka square (वर्ग) kitna hota hai?",
         "options": ["478", "482", "480", "484"], "correct": 3},
        {"q": "6 ka square (वर्ग) kitna hota hai?",
         "options": ["36", "32", "34", "42"], "correct": 0},
        {"q": "28 ka square (वर्ग) kitna hota hai?",
         "options": ["784", "780", "793", "782"], "correct": 0},
        {"q": "27 ka square (वर्ग) kitna hota hai?",
         "options": ["729", "720", "738", "723"], "correct": 0},
        {"q": "15 ka square (वर्ग) kitna hota hai?",
         "options": ["223", "229", "216", "225"], "correct": 3},
        {"q": "18 ka square (वर्ग) kitna hota hai?",
         "options": ["326", "333", "335", "324"], "correct": 3},
        {"q": "25 ka square (वर्ग) kitna hota hai?",
         "options": ["627", "625", "629", "621"], "correct": 1},
        {"q": "400 ka 5% kitna hota hai?",
         "options": ["15", "20", "25", "45"], "correct": 1},
        {"q": "100 ka 40% kitna hota hai?",
         "options": ["60", "40", "65", "50"], "correct": 1},
        {"q": "50 ka 5% kitna hota hai?",
         "options": ["27", "2", "12", "17"], "correct": 1},
        {"q": "150 ka 30% kitna hota hai?",
         "options": ["45", "50", "30", "55"], "correct": 0},
        {"q": "80 ka 10% kitna hota hai?",
         "options": ["8", "33", "28", "3"], "correct": 0},
        {"q": "200 ka 75% kitna hota hai?",
         "options": ["135", "140", "150", "145"], "correct": 2},
        {"q": "1000 ka 75% kitna hota hai?",
         "options": ["750", "730", "745", "735"], "correct": 0},
        {"q": "400 ka 60% kitna hota hai?",
         "options": ["240", "220", "230", "225"], "correct": 0},
        {"q": "200 ka 15% kitna hota hai?",
         "options": ["35", "30", "25", "50"], "correct": 1},
        {"q": "250 ka 50% kitna hota hai?",
         "options": ["150", "120", "110", "125"], "correct": 3},
        {"q": "120 ka 25% kitna hota hai?",
         "options": ["20", "10", "30", "45"], "correct": 2},
        {"q": "800 ka 50% kitna hota hai?",
         "options": ["400", "405", "385", "380"], "correct": 0},
        {"q": "500 ka 30% kitna hota hai?",
         "options": ["140", "150", "170", "175"], "correct": 1},
        {"q": "400 ka 25% kitna hota hai?",
         "options": ["100", "90", "85", "110"], "correct": 0},
        {"q": "50 ka 60% kitna hota hai?",
         "options": ["40", "30", "20", "10"], "correct": 1},
        {"q": "100 ka 10% kitna hota hai?",
         "options": ["35", "0", "10", "25"], "correct": 2},
        {"q": "300 ka 40% kitna hota hai?",
         "options": ["105", "110", "120", "140"], "correct": 2},
        {"q": "600 ka 50% kitna hota hai?",
         "options": ["300", "315", "305", "295"], "correct": 0},
        {"q": "100 ka 20% kitna hota hai?",
         "options": ["30", "25", "20", "0"], "correct": 2},
        {"q": "120 ka 10% kitna hota hai?",
         "options": ["12", "32", "17", "2"], "correct": 0},
        {"q": "120 ka 15% kitna hota hai?",
         "options": ["23", "28", "18", "3"], "correct": 2},
        {"q": "150 ka 60% kitna hota hai?",
         "options": ["90", "80", "100", "110"], "correct": 0},
        {"q": "800 ka 25% kitna hota hai?",
         "options": ["200", "185", "225", "195"], "correct": 0},
        {"q": "300 ka 25% kitna hota hai?",
         "options": ["55", "75", "60", "100"], "correct": 1},
        {"q": "100 ka 50% kitna hota hai?",
         "options": ["40", "75", "50", "60"], "correct": 2},
        {"q": "50 ka 40% kitna hota hai?",
         "options": ["45", "40", "20", "5"], "correct": 2},
        {"q": "100 ka 15% kitna hota hai?",
         "options": ["40", "15", "5", "30"], "correct": 1},
        {"q": "100 ka 75% kitna hota hai?",
         "options": ["95", "100", "80", "75"], "correct": 3},
        {"q": "500 ka 25% kitna hota hai?",
         "options": ["110", "105", "120", "125"], "correct": 3},
        {"q": "1000 ka 60% kitna hota hai?",
         "options": ["580", "625", "585", "600"], "correct": 3},
        {"q": "400 ka 75% kitna hota hai?",
         "options": ["300", "315", "290", "305"], "correct": 0},
        {"q": "100 ka 60% kitna hota hai?",
         "options": ["75", "60", "80", "70"], "correct": 1},
        {"q": "200 ka 40% kitna hota hai?",
         "options": ["90", "105", "70", "80"], "correct": 3},
        {"q": "800 ka 5% kitna hota hai?",
         "options": ["35", "65", "30", "40"], "correct": 3},
        {"q": "50 ka 50% kitna hota hai?",
         "options": ["40", "50", "25", "45"], "correct": 2},
        {"q": "300 ka 15% kitna hota hai?",
         "options": ["65", "55", "45", "35"], "correct": 2},
        {"q": "800 ka 15% kitna hota hai?",
         "options": ["135", "100", "120", "115"], "correct": 2},
        {"q": "1000 ka 20% kitna hota hai?",
         "options": ["195", "180", "220", "200"], "correct": 3},
        {"q": "100 ka 25% kitna hota hai?",
         "options": ["25", "5", "20", "50"], "correct": 0},
        {"q": "250 ka 20% kitna hota hai?",
         "options": ["55", "50", "45", "60"], "correct": 1},
        {"q": "250 ka 10% kitna hota hai?",
         "options": ["25", "30", "5", "40"], "correct": 0},
        {"q": "120 ka 20% kitna hota hai?",
         "options": ["24", "49", "4", "44"], "correct": 0},
        {"q": "80 ka 5% kitna hota hai?",
         "options": ["29", "19", "4", "14"], "correct": 2},
        {"q": "200 ka 25% kitna hota hai?",
         "options": ["40", "65", "50", "75"], "correct": 2},
        {"q": "500 ka 60% kitna hota hai?",
         "options": ["290", "320", "305", "300"], "correct": 3},
        {"q": "50 ka 20% kitna hota hai?",
         "options": ["25", "0", "10", "35"], "correct": 2},
        {"q": "250 ka 75% kitna hota hai?",
         "options": ["197", "187", "172", "182"], "correct": 1},
        {"q": "300 ka 20% kitna hota hai?",
         "options": ["55", "60", "40", "85"], "correct": 1},
        {"q": "1000 ka 25% kitna hota hai?",
         "options": ["235", "250", "245", "275"], "correct": 1},
        {"q": "120 ka 50% kitna hota hai?",
         "options": ["70", "65", "60", "40"], "correct": 2},
        {"q": "1000 ka 15% kitna hota hai?",
         "options": ["150", "165", "170", "145"], "correct": 0},
        {"q": "800 ka 40% kitna hota hai?",
         "options": ["320", "335", "340", "325"], "correct": 0},
        {"q": "400 ka 20% kitna hota hai?",
         "options": ["90", "105", "80", "100"], "correct": 2},
        {"q": "800 ka 10% kitna hota hai?",
         "options": ["90", "95", "75", "80"], "correct": 3},
        {"q": "120 ka 5% kitna hota hai?",
         "options": ["11", "31", "6", "21"], "correct": 2},
        {"q": "800 ka 60% kitna hota hai?",
         "options": ["480", "475", "495", "490"], "correct": 0},
        {"q": "50 ka 10% kitna hota hai?",
         "options": ["10", "15", "5", "25"], "correct": 2},
        {"q": "400 ka 10% kitna hota hai?",
         "options": ["65", "20", "30", "40"], "correct": 3},
        {"q": "150 ka 25% kitna hota hai?",
         "options": ["52", "27", "37", "17"], "correct": 2},
        {"q": "200 ka 30% kitna hota hai?",
         "options": ["85", "60", "40", "55"], "correct": 1},
        {"q": "600 ka 25% kitna hota hai?",
         "options": ["175", "170", "150", "130"], "correct": 2},
        {"q": "1000 ka 5% kitna hota hai?",
         "options": ["75", "30", "50", "55"], "correct": 2},
        {"q": "800 ka 30% kitna hota hai?",
         "options": ["265", "230", "240", "225"], "correct": 2},
        {"q": "120 ka 75% kitna hota hai?",
         "options": ["95", "100", "105", "90"], "correct": 3},
        {"q": "200 ka 20% kitna hota hai?",
         "options": ["35", "45", "60", "40"], "correct": 3},
        {"q": "80 ka 25% kitna hota hai?",
         "options": ["45", "35", "20", "5"], "correct": 2},
        {"q": "500 ka 15% kitna hota hai?",
         "options": ["75", "65", "60", "95"], "correct": 0},
        {"q": "600 ka 60% kitna hota hai?",
         "options": ["385", "340", "360", "345"], "correct": 2},
        {"q": "50 ka 15% kitna hota hai?",
         "options": ["32", "17", "12", "7"], "correct": 3},
        {"q": "500 ka 5% kitna hota hai?",
         "options": ["30", "25", "10", "40"], "correct": 1},
        {"q": "400 ka 40% kitna hota hai?",
         "options": ["185", "160", "170", "175"], "correct": 1},
        {"q": "250 ka 15% kitna hota hai?",
         "options": ["22", "62", "47", "37"], "correct": 3},
        {"q": "250 ka 60% kitna hota hai?",
         "options": ["145", "150", "160", "135"], "correct": 1},
        {"q": "400 ka 30% kitna hota hai?",
         "options": ["120", "115", "125", "140"], "correct": 0},
        {"q": "800 ka 75% kitna hota hai?",
         "options": ["585", "615", "600", "590"], "correct": 2},
        {"q": "600 ka 40% kitna hota hai?",
         "options": ["225", "240", "245", "230"], "correct": 1},
        {"q": "300 ka 30% kitna hota hai?",
         "options": ["75", "105", "100", "90"], "correct": 3},
        {"q": "120 ka 60% kitna hota hai?",
         "options": ["82", "92", "77", "72"], "correct": 3},
        {"q": "400 ka 15% kitna hota hai?",
         "options": ["80", "50", "60", "75"], "correct": 2},
        {"q": "600 ka 75% kitna hota hai?",
         "options": ["475", "435", "460", "450"], "correct": 3},
        {"q": "100 ka 5% kitna hota hai?",
         "options": ["30", "5", "20", "10"], "correct": 1},
        {"q": "150 ka 5% kitna hota hai?",
         "options": ["22", "12", "7", "27"], "correct": 2},
        {"q": "800 ka 20% kitna hota hai?",
         "options": ["175", "165", "180", "160"], "correct": 3},
        {"q": "150 ka 10% kitna hota hai?",
         "options": ["10", "15", "35", "0"], "correct": 1},
        {"q": "500 ka 20% kitna hota hai?",
         "options": ["110", "100", "120", "115"], "correct": 1},
        {"q": "500 ka 75% kitna hota hai?",
         "options": ["370", "375", "385", "380"], "correct": 1},
        {"q": "600 ka 5% kitna hota hai?",
         "options": ["40", "30", "35", "45"], "correct": 1},
        {"q": "80 ka 75% kitna hota hai?",
         "options": ["75", "60", "65", "70"], "correct": 1},
        {"q": "200 ka 60% kitna hota hai?",
         "options": ["110", "145", "115", "120"], "correct": 3},
        {"q": "250 ka 40% kitna hota hai?",
         "options": ["95", "105", "120", "100"], "correct": 3},
    ],
    "Gaming": [
        {"q": "\"BGMI\" का पूरा नाम क्या है?",
         "options": ["Battlegrounds Mobile India", "Big Games Mobile India", "Battle Group Mobile India", "Best Game Mobile India"], "correct": 0},
        {"q": "शतरंज (Chess) में राजा (King) कितने घर एक बार में चल सकता है (सामान्य चाल में)?",
         "options": ["1", "2", "3", "जितने चाहे"], "correct": 0},
        {"q": "\"Free Fire\" aur \"BGMI\" jaise games kis category mein aate hain?",
         "options": ["Puzzle", "Battle Royale", "Racing", "Card Game"], "correct": 1},
        {"q": "PUBG/BGMI jaise games ko kis genre mein rakha jaata hai?",
         "options": ["Racing", "Battle Royale", "Puzzle", "Strategy"], "correct": 1},
        {"q": "\"Minecraft\" game mein players kya karte hain mainly?",
         "options": ["Racing cars", "Building aur Survival", "Card battles", "Football khelna"], "correct": 1},
        {"q": "Ludo khelne mein kitne dice (pasa) normally use hota hai?",
         "options": ["1", "2", "3", "4"], "correct": 0},
    ],
    "AI": [
        {"q": "AI का पूरा नाम क्या है?",
         "options": ["Artificial Intelligence", "Automated Internet", "Advanced Information", "Applied Interface"], "correct": 0},
        {"q": "Machine Learning किसका हिस्सा है?",
         "options": ["Hardware Engineering", "Artificial Intelligence", "Web Design", "Networking"], "correct": 1},
        {"q": "Claude AI ko kis company ne banaya hai?",
         "options": ["Google", "OpenAI", "Anthropic", "Meta"], "correct": 2},
        {"q": "AI chatbot se baat karne ke process ko kya kehte hain?",
         "options": ["Coding", "Prompting", "Streaming", "Rendering"], "correct": 1},
        {"q": "\"NLP\" (AI ke context mein) ka full form kya hai?",
         "options": ["Natural Language Processing", "New Learning Process", "Network Language Program", "Neural Logic Processing"], "correct": 0},
        {"q": "Self-driving cars kis technology par based hote hain?",
         "options": ["Blockchain", "Artificial Intelligence", "Cloud Storage", "5G Network"], "correct": 1},
        {"q": "AI mein \"training data\" ka use kis liye hota hai?",
         "options": ["Model ko sikhane ke liye", "Internet speed badhane ke liye", "Battery bachane ke liye", "Storage khali karne ke liye"], "correct": 0},
    ],
}

def get_categories() -> list:
    return list(QUESTION_BANK.keys())


def pick_question(exclude_texts: set = None, avoid_category: str = None) -> dict:
    """Returns {"category", "question", "options", "correct_index"}.

    Tries hard not to repeat a question already used in this group
    (exclude_texts) and not to repeat the immediately-previous category
    (avoid_category), without ever looping forever: each category is
    tried at most once per call."""
    exclude_texts = exclude_texts or set()
    categories = get_categories()

    ordered = list(categories)
    random.shuffle(ordered)
    if avoid_category and len(ordered) > 1:
        ordered = [c for c in ordered if c != avoid_category] + (
            [avoid_category] if avoid_category in ordered else []
        )

    for category in ordered:
        pool = [q for q in QUESTION_BANK[category] if q["q"] not in exclude_texts]
        if pool:
            chosen = random.choice(pool)
            return {
                "category": category,
                "question": chosen["q"],
                "options": chosen["options"],
                "correct_index": chosen["correct"],
            }

    # Every question in every category has already been used in this
    # group at some point — allow a repeat rather than sending nothing.
    category = random.choice(categories)
    chosen = random.choice(QUESTION_BANK[category])
    return {
        "category": category,
        "question": chosen["q"],
        "options": chosen["options"],
        "correct_index": chosen["correct"],
    }
